# Generated by Django 3.0.7 on 2020-11-20 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='position',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='category',
            name='Description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='Category_Images/default.jpg', upload_to='Category_Images'),
        ),
        migrations.AddField(
            model_name='category',
            name='Title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Description',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Image',
            field=models.ImageField(default='Course_Images/default.jpg', upload_to='Course_Images'),
        ),
        migrations.AddField(
            model_name='course',
            name='Level',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Time_Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Title',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='Course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='Position',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='Title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lesson',
            name='Video_id',
            field=models.FileField(default='', upload_to='video_lessons'),
        ),
    ]
